apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    access: proxy
    url: ${GRAFANA_DB_HOST}:${GRAFANA_DB_PORT}
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: ${GRAFANA_DB_SSLMODE}
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1800
      timescaledb: true
    isDefault: true
    editable: false
